name = "CheckedCalls"
uuid = "6490f8d2-1475-45bb-865d-edb65413071d"
version = "0.1.0"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[extensions]
CheckedCallsChainRulesCoreExt = "ChainRulesCore"
CheckedCallsChangesOfVariablesExt = "ChangesOfVariables"
CheckedCallsForwardDiffExt = "ForwardDiff"
CheckedCallsInverseFunctionsExt = "InverseFunctions"

[compat]
ChainRulesCore = "1"
ChangesOfVariables = "0.1"
ForwardDiff = "0.8, 0.9, 0.10, 1"
InverseFunctions = "0.1"
julia = "1.10"
